### ISSUE TITLE
error C1083: Cannot open include file: 'ntifs.h'

### ISSUE THREAD

**Issue by johnjohnsp1** [ZeroMemoryEx/Tokenizer#1]
hi,
cannot compile due to missing ntifs.h file:

Build started...
1>------ Build started: Project: Tokenizer, Configuration: Debug x64 ------
1>driver.c
1>C:\temp\Tokenizer\Tokenizer\driver.c(1,10): fatal  error C1083: Cannot open include file: 'ntifs.h': No such file or directory
1>Done building project "Tokenizer.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 2:32 PM and took 02.133 seconds ==========

using windows 10 with VStudio 2022, even if i add manually the file ntifs.h which is found inside Windows Kit Driver folder at:

C:\Program Files (x86)\Windows Kits\10\Include\10.0.25314.0\km\

does not work, im missing something or ?
any idea ? 

thanks for share the idea and the code

**Comment by ZeroMemoryEx** [comment]
Hello @johnjohnsp1 , Make sure you install SDK and WDK 
- https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk

**Comment by ZeroMemoryEx** [comment]
Hello @johnjohnsp1  , Make sure you install WDK

- https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk

**Comment by johnjohnsp1** [comment]
having both WDK and SDk installed,
now im getting this error

Build started...
1>------ Build started: Project: Tokenizer, Configuration: Release x64 ------
1>driver.c
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared\ntdef.h(197,1): fatal  error C1189: #error:  "No Target Architecture"
1>Done building project "Tokenizer.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 3:07 PM and took 00.879 seconds ==========

**Comment by ZeroMemoryEx** [comment]
can you verify the header file ntdef.h exist in C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared\ ?

**Comment by johnjohnsp1** [comment]
yes, exist

￼

**Comment by ZeroMemoryEx** [comment]
to avoid this kind of problem i may upload a compiled version , Please use VirtualBox because the driver may cause the OS to become unstable at some point due to incompatibility with some versions of Windows.

run the following commands in administrator command prompt to disable the signature check
* bcdedit /set nointegritychecks on
* bcdedit /set testsigning on

after you reboot download  OSRLOADER  from here , then load the driver with it
* https://www.osronline.com/article.cfm%5Earticle=157.htm

**Comment by ZeroMemoryEx** [comment]
here is the compiled version @johnjohnsp1 
- https://github.com/ZeroMemoryEx/Tokenizer/releases/tag/compiled

**Comment by johnjohnsp1** [comment]
thanks, i will try with commands you suggest, actually im on esxi vmware platform

**Comment by ZeroMemoryEx** [comment]
alright , if it worked leave a message to close the ticket

**Comment by johnjohnsp1** [comment]
the compiled version is working but even with both command executed vstudio still issue with fatal  error C1189: #error:  "No Target Architecture".
i have downloaded the OSRloader but the driver is not compiled so i cannot load anything.
anyways i think is just my problem no idea why but since you compiled version is working is fine.

**Comment by ZeroMemoryEx** [comment]
i have compiled them both for you, check the project Releases 

* https://github.com/ZeroMemoryEx/Tokenizer/releases

The steps above are just for how to use them, not for solving the issue.

**Comment by ZeroMemoryEx** [comment]
![image](https://user-images.githubusercontent.com/60795188/226393373-f4b743a3-7a0e-4833-8804-ff04453b5930.png)

**Comment by johnjohnsp1** [comment]
thanks for compiled version, tested em both and are working.
can close the case

**Comment by ZeroMemoryEx** [comment]
Happy to hear that! If you have any feature suggestions or problems, don't hesitate to open an issue ticket
